version: '3.8'

services:
  case-analitica-front:
    image: ghcr.io/case-analitica/case-analitica-front:latest
    container_name: "case-analitica-front-app"
    ports:
      - 80:80
    expose:
      - 80
    networks:
      - ca-networks

networks:
  ca-networks:
    driver: bridge
