version: '3.8'

services:
  case-analitica-front:
    image: case-analitica-app-front
    container_name: case-analitica-front-service
    build: .
    ports:
      - 8081:80

networks:
  ca-networks:
    driver: bridge
