version: '3.8'

services:
  case-analitica-front:
    image: case-analitica-app-front:0.0.1
    container_name: "case-analitica-front-service"
    build: .
    ports:
      - 4200:80
    expose:
      - 80
    networks:
      - ca-networks

networks:
  ca-networks:
    driver: bridge
